title: Oskar Floeck
author:
  name: Have a question?
  email: oskar.floeck@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://floeck.dev" # the base hostname & protocol for your site, e.g. http://example.com
enforce_ssl: floeck.dev
description: > # this means to ignore newlines until "show_excerpts:"
  “And those who were seen dancing were thought to be insane by those who could not hear the music.” 
  ― Friedrich Nietzsche


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: dark
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: anon_avo
    github:  floeck
    inkedin: oskar.floeck@gmail.com
    linkedin_username: oskar.floeck@gmail.com
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - portfolio.md
 - about.md
 - contact.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
